
package GUI;
/*
aqui se encuentran todas y cada una de las diferentes librerias que fueron utilizadas para la
realizacion de nuestras interfaces, y el llamado de los diferentes packages donde haciamos el llamado de los
diferentes metodos para la buen funcionamiento de la logica de esta interfaz 
*/

import LOGICA.gestionar_Cliente;
import registros.Cliente;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import logica.gestionar_Proveedor;
import static main.main.men;
import registros.Proveedor;
//////////////////////////////////////////////////////////////////////////////////////////////
/**
 *@author Moreno Romero Miguel Angel 
 * miguel.romero@correounivalle.edu.co
 *@author Valencia Pardo Sergio 
 * sergio.pardo@correounivalle.edu.co
 */
/////////////////////////////////////////////////////////////////////////////////////////////
/*
nos encontramos nuestra clase principal "GUI_Proveedor " que es la encargada de contener 
la fucionalidad y metodos necesarios para la funcioniladad por la cual se tuvo encuenta su creacion y es el buen 
funcionamiento de la modificacion del archivo.txt
*/
public class GUI_Proveedor extends javax.swing.JFrame {
/*
ahora lo que haremos es inicializar una variable "Filas" que es la que nos ayudara para determinar 
el numero de filas en el cual nosotros hemos seleccionado para poder realizar la respectiva operacion 
solo sobre la fila seleccionada 

*/     
    
 int filas;
    
/*
ahora una vez inicializada nuestra variable tipo entero, debemos de llamar nuestros metodos antes inicializados 
para poder tener accesos a ellos y poder operar sobre nuestro archivo de texto adecuado y correcto     
*/
    Proveedor  m =new Proveedor();
    gestionar_Proveedor g = new gestionar_Proveedor();  
    DefaultTableModel nuestraTabla;   
    Vector almacenar = new Vector();
   
 /*
una vez que hemos declarado nuestra variable tipo entero (int) y llamado  nuestros metodos antes incializados 
procedemos a inicializar nuestra clase que estara declara al final de todo el codigo que es la responsable 
de pasar una imagen de fondo a nuestro panel principal 
*/   
 
    imagen_fondo cgd = new imagen_fondo();
   
    
/*
una vez declarado todas los metodos que vamos a utilizar procedemos a inicializar en nuestro "CONSTRUCTOR" la clase 
responsable de inicializar nuestos elementos del JFrame, el fondo de nuestro JPanel y de colocar los datos visibles
en nuestra JTable apenas aparezca nuestra interfaz.    
*/
    
    
    
    
    public GUI_Proveedor() {
        
      
        
         this.setContentPane(cgd);
         
        initComponents();
        setLocationRelativeTo(null);
        llenarCombox();
        llenarCombox2();
        almacenar.addElement("Nombre");             
         almacenar.addElement("Codigo");
         almacenar.addElement("Productos");
         almacenar.addElement("Cantidad");
         almacenar.addElement("Precio");
         
         nuestraTabla= new DefaultTableModel(almacenar,0);
         
         Tabla.setModel(g.mostrar());
        
    }

   /*
    este metodo nos ayuda a llenar el comboBox para la seleccion de productos disponibles que dispone el supermercado 
    de un maner dinamica donde se llena el comboBox dependiendo de lo que haya en el archivo de texto "Productos.txt"
    */ 
    public void llenarCombox(){
             
                
        try {
            
          BufferedReader br = new BufferedReader(new FileReader("Productos.txt"));
          for(int i =1;i<=100;i++){
              
            //combo.addItem(String.valueOf(i));
          String linea ;
         JComboBox<String> d = new JComboBox<String>();
       while((linea = br.readLine()) != null) {
            StringTokenizer tokens = new StringTokenizer(linea," || ");
            combo.addItem(tokens.nextElement().toString());
            //System.out.println(tokens.nextToken());
           

            }
      
           
           
          }
          br.close();
        } catch (Exception e) {
        }
        
    }
    
     public void llenarCombox2(){
         for (int i=0;i<100;i++){
             combo2.addItem(String.valueOf(i).toString());
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Agregar = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        Modificar = new javax.swing.JButton();
        texto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Producto = new javax.swing.JTextField();
        Atras = new javax.swing.JButton();
        precio = new javax.swing.JTextField();
        Eliminar = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESA LA INFORMACION PARA SURTIR EL SUPERMERCADO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        Tabla.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(153, 153, 255)));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cantidad", "Precio", "Codigo", "Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Tabla.setOpaque(false);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        Agregar.setBackground(new java.awt.Color(204, 204, 255));
        Agregar.setText("LISTAR ");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });

        Id.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo"));
        Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdKeyTyped(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(204, 204, 255));
        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        texto.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));
        texto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textoCaretUpdate(evt);
            }
        });
        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCTOS NECESARIOS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" PARA SURTIR");

        combo2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });

        Producto.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));
        Producto.setOpaque(true);

        Atras.setBackground(new java.awt.Color(204, 204, 255));
        Atras.setText("ATRAS");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        precio.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio"));
        precio.setOpaque(true);

        Eliminar.setBackground(new java.awt.Color(204, 204, 255));
        Eliminar.setText("ELIMINAR");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        cantidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));
        cantidad.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(Producto)
                            .addComponent(texto))))
                .addGap(0, 76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(139, 139, 139))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
 /*
ahora en nuestro boton de "AGREGAR" declaramos un condicional para tener presente que todos los campos  y los datos que se encuentra
en cada uno de los "JTextField" esten llenos, donde si estos estan vacios no dejara que hagas el respectivo registro 
una vez inicializada nuestrra tabla procedemos a declarar varibles de tipo "String"  para escribirlos en el archivo ".TXT" 
suministrada por el usuario.      
*/        
        if (Nombre.getText().trim().isEmpty() ||  Id.getText().trim().isEmpty() || Producto.getText().trim().isEmpty() || cantidad.getText().trim().isEmpty() || precio.getText().trim().isEmpty()) {
    
            JOptionPane.showMessageDialog(null, "todos los campos son obligatorios");
    
        }else{
            
        nuestraTabla = new DefaultTableModel();
       
        String nombre = Nombre.getText(); 
          String id = Id.getText();
            String prod = Producto.getText();
            String precui = precio.getText();
            String cantd = cantidad.getText();
            
          
             
                      m.setNombre(nombre);          
                      m.setIdentificacion(id);
                      m.setProductos(prod);
                      m.setPrecio(precui);
                      m.setUnidades(cantd);
                      
                      
                      
                      g.guardar(m);
                      g.guardarArchivo(m);          
                        
                     JOptionPane.showMessageDialog(null, "se ha guardado el registro con exito");
   //en esta parte lo que hacemos es decirle que despues de AGREGAR los datos nos deje los campos del JTectField vacios         
                     Nombre.setText("");                   
                      Id.setText("");
                       Producto.setText("");
                        precio.setText("");
                         cantidad.setText("");
                    
                      Tabla.setModel(g.mostrar());
                          
                      }
        
         
              
                 // TODO add your handling code here:
    }//GEN-LAST:event_AgregarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
     /*
        aqui mandamos a llamar nuestro ventana que es la que nos permite modificar la informacion de la respectiva tabla y la reescritura de los archivos
        */
     
        setVisible(false);
        new GUI_M_Proveedor().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_ModificarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
/*
En este metodo tendremos el evento de que cuando le demos clic al tabla este no solo nos señale la fila 
sino que nos traiga la ifomacion seleccionada en cada uno de los campos donde corresponde la respectiva informacion 
donde es importar tener en cuenta que seguimos trabajando con lamatriz antes definida donde para taer el dato 
es necesario tener en cuenta la posicion dekl mismo la cual la pasaremos a nuestra variable entera(int) antes inicializada 
llamada "Filas".        
*/   
        
       
        Agregar.setEnabled(false);   
        this.nuestraTabla= (DefaultTableModel)Tabla.getModel();
         
        int selecionado = Tabla.getSelectedRow();
                      
         
                  
            filas= selecionado;
   
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaMouseClicked

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
 /*
ahora lo que hacemos es declarar una variable entero y declaramos metodos boolean para decirle que todos los campos son obligatorios 
y que no se permite que estos esten vacios es decir que la informacion dbe ser de tipo string o numerica sin importar que el dato este escrito 
como "VACIO " o "NULL" pero en si esto nos ayuda a que el usuario nos ingrese un valor de manera obligatoria         
*/
        int key = evt.getKeyChar();

    boolean mayusculas = key >= 65 && key <= 90;
    boolean minusculas = key >= 97 && key <= 122;
    boolean espacio = key == 32;
            
     if (!(minusculas || mayusculas || espacio))
    {
        evt.consume();
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_NombreKeyTyped

    private void IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_IdKeyTyped

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
/*
ahora en esta parte del escucha del boton donde le decimos que cuando hagamos clic nos desactive la interfaz actual 
y nos muestre la anterior estos llamados es lo que nos permite el desplazamiento entre las interfaces graficas al usuario
despues de realizar alguna operacion         
*/
         Agregar.setEnabled(true);
         setVisible(false);
        men.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasActionPerformed

    private void textoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textoCaretUpdate
  /*
aqui lo que hacemos es en campo de busqueda que es un "JTextField" lo cual lo designaremos que nos busque por nombre,
nos traiga eso que el usuario ingresa en el campo y lo compare con la columna y las filas que conforman a Nombre, donde si hay alguna coincidencia
este nos ilumine la fila.        
*/
  
           String letras = texto.getText();

       for(int i=0; i < Tabla.getRowCount();i++){
           
           if(Tabla.getValueAt(i,0).equals(letras)){
               
               Tabla.changeSelection(i,0,false,false);
               
           }
       }



        // TODO add your handling code here:
    }//GEN-LAST:event_textoCaretUpdate

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
   /*
        para nuestro comboBox que es el encargado de llenar la respectiva cantida lo llenamos con valores de 0 a 100 
       
        */
        String cantidad_producto= combo2.getSelectedItem().toString();
    cantidad.setText(cantidad_producto);
   
// TODO add your handling code here:
    }//GEN-LAST:event_combo2ActionPerformed

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
    //aqui declaramos al igual que en agregar o actualizar los respectivos metodos que nos permitan borrar la fila de informacion antes seleccionada    
        nuestraTabla.removeRow(Tabla.getSelectedRow());
        
        try {
            
            String h = "Proveedor.txt";
            BufferedWriter bw = new BufferedWriter(new FileWriter(h));
            
            for(int i =0;i<Tabla.getRowCount();i++){
                for(int j=0;j<Tabla.getColumnCount();j++){
                    bw.write((String)(Tabla.getValueAt(i,j)));
                    if(j<Tabla.getColumnCount()-1){
                        bw.write(" || ");
                        
                    }
                }
                bw.newLine();
            }
            bw.close();
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null,"los datos NO han sido borrados con exito");
            
        }
        
        JOptionPane.showMessageDialog(null,"los datos han sido borrados con exito");
        //aqui le decimos al boton de agregar que se vuelva ha activar
        Agregar.setEnabled(true);    


        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
    //ahora aqui lo que hacemos es pasarle a nuestro comboBox de productos el metodo anteriormente declarado que es el que nos 
    //permite llenar la categoria productos desde lo que esta ingresado en un archivo de productos 
        
        String mercancia = combo.getSelectedItem().toString();
     
       
        Producto.setText(mercancia);
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Proveedor().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Agregar;
    private javax.swing.JButton Atras;
    public javax.swing.JButton Eliminar;
    public javax.swing.JTextField Id;
    public javax.swing.JButton Modificar;
    public javax.swing.JTextField Nombre;
    private javax.swing.JTextField Producto;
    public javax.swing.JTable Tabla;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField precio;
    public javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
/*
ahora aqui declaramos nuestra clase "Imagen_Fondo" que es la que utilizaremos para pasar le una imagen anuestro JPanel 
para darle un mejor entorno visual a nuestra intrfaz grafica la cual fue inicializada al inicio del codigo y llamada
para su ejecucion en el constructor.     
*/
class imagen_fondo extends JPanel{
    private Image imagen;
    //metodo 
    public void paint (Graphics g){
        imagen = new ImageIcon(getClass().getResource("/imagenes/fondo_general.png")).getImage();
        g.drawImage(imagen,0, 0, getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
    
}

}
